### ISSUE TITLE
Uncaught TypeError: Cannot read property 'openScopes' of undefined

### ISSUE THREAD

**Issue by nibushibu** [raccy/show-ideographic-space#5]
SCSSファイルを編集中に、
```
.class-name {}
```
などと入力すると、そのファイルを保存するまでは、改行を使用とリターンキーを押しても下記のようなエラーが表示され改行が挿入できなくなるようでした。
こちらのパッケージの問題ではないかもしれませんが、念のためご報告しました。

**Atom Version**: 0.202.0
**System**: Mac OS X 10.10.3
**Thrown From**: [show-ideographic-space](https://github.com/raccy/show-ideographic-space) package, v0.1.7

### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:755

TypeError: Cannot read property 'openScopes' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:555:49)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:515:27)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow [as originalBuildTokenizedLineForRow] (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:506:19)
  at TokenizedBuffer.tokenizedBuffer.buildTokenizedLineForRow (/Users/nibushibu/.atom/packages/show-ideographic-space/lib/show-ideographic-space-manager.coffee:42:24)
  at TokenizedBuffer.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:459:34)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLinesForRows (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:468:10)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:369:32)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:624:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:532:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:452:43)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:730:31
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:775:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:750:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1136:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:769:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1954:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1928:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:767:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:727:21)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher.js:142:26
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:750:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1136:26)
  at BracketMatcher.module.exports.BracketMatcher.insertNewline (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher.js:139:21)
  at TextEditor.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher.js:3:61)
  at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:76:20)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:593:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:305:34
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:750:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1136:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
  9x -0:20.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.5.0 emmet:select-previous-item (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14 core:cut (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:copy (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.6.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:03.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:03.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:paste (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:02.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:00.9.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "css-color-highlight",
      "jslint",
      "crosshairs",
      "term",
      "pain-split",
      "css-color-highlighting",
      "atom-lint",
      "tab-switcher",
      "caniuse",
      "term2",
      "atom-beautify",
      "linter-tidy",
      "linter-htmlhint",
      "resize-panes",
      "white-cursor",
      "linter-scss-lint",
      "space-tab",
      "japanese-menu",
      "tree-view-filter",
      "tool-bar",
      "tool-bar-main",
      "grammar-token-limit"
    ],
    "themes": [
      "atom-dark-ui-slim",
      "monokai"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.4
ascii-codes, v0.3.3
atom-alignment, v0.12.1
atom-color-highlight, v3.0.9
atom-dark-ui-slim, v0.47.1
autocomplete-paths, v1.0.2
bezier-curve-editor, v0.7.1
color-picker, v2.0.2
emmet, v2.3.10
file-icons, v1.5.5
filetype-color, v0.1.4
highlight-column, v0.4.1
highlight-line, v0.10.2
html-entities, v0.4.0
html-img, v0.4.0
japanese-wrap, v0.2.7
language-actionscript, v0.2.0
linter, v0.12.6
linter-coffeelint, v0.2.4
linter-csslint, v0.0.13
linter-php, v0.0.15
minimap, v4.9.0
minimap-git-diff, v4.1.3
monokai, v0.14.0
project-manager, v1.15.7
recent-files, v0.3.0
regex-railroad-diagram, v0.7.4
set-syntax, v0.3.0
show-ideographic-space, v0.1.7
tree-view-finder, v0.2.1

# Dev
No dev packages
```

**Comment by raccy** [comment]
手元で試してみましたが、現象が発生しませんでした。
なにか、必ず発生させられる手順があれば教えて下さい。
また、パッケージを無効化した状態でReloadしたあとも発生するとかかもわかれば、
パッケージが原因かどうかもわかりますので、情報をいただければと思います。

**Comment by raccy** [comment]
Atom側のAPIが変わって、根本的に動かないことが判明しました。
そっちに統合してますので、 そちらを見てください。 #7

**Comment by nibushibu** [comment]
ご返答ありがとうございます！ :+1:
