### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isComment' of undefined

### ISSUE THREAD

**Issue by raccy** [raccy/show-ideographic-space#6]
It causes only when show-ideographic-space is enable.
Maybe there is a bug on the package, not Atom core.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'isComment' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:755

TypeError: Cannot read property 'isComment' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.isFoldableCodeAtRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:429:71)
  at TokenizedBuffer.module.exports.TokenizedBuffer.isFoldableAtRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:424:19)
  at TokenizedBuffer.module.exports.TokenizedBuffer.updateFoldableStatus (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:412:25)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:377:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:624:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:789:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:753:14)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1136:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:769:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1958:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1928:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:767:19)
  at TextEditor.module.exports.TextEditor.pasteText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2326:19)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:paste (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:437:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:305:34
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:750:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1136:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:17.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:17 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:17 snippets:expand (atom-text-editor.editor.is-focused)
     -0:17 editor:indent (atom-text-editor.editor.is-focused)
     -0:16.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:16.5.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:16.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:14.8.0 core:move-up (atom-text-editor.editor.is-focused)
  7x -0:14.2.0 core:select-down (atom-text-editor.editor.is-focused)
  2x -0:12.9.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:11.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:11.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:11.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:10.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:00.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "trailing-spaces",
      "linter-shellcheck",
      "linter-pep8",
      "linter-jscs",
      "linter-jshint",
      "terminal-panel",
      "autocomplete-clang",
      "linter-hlint",
      "linter-javac",
      "linter-js-yaml",
      "linter-mcs",
      "linter-scalac",
      "linter-tidy",
      "linter-tslint",
      "linter-erb",
      "linter-csslint",
      "remote-edit",
      "atom-rails",
      "rails-rspec",
      "highlight-column",
      "localization",
      "atom-beautify",
      "atom-charcode",
      "atom-pronama-chan",
      "autocomplete-ruby",
      "japanese-menu",
      "language-haskell"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontFamily": "'Migu 2M'",
    "showInvisibles": true,
    "showIndentGuide": true,
    "invisibles": {},
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "tabLength": 8,
    "fontSize": 14,
    "softTabs": false
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.6.2
Sublime-Style-Column-Selection, v1.3.0
atom-color-highlight, v3.0.9
autocomplete-haskell, v0.4.2
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
autocomplete-python, v0.4.1
color-picker, v2.0.2
editorconfig, v1.0.0
file-icons, v1.5.5
haskell-ghc-mod, v0.6.2
highlight-selected, v0.9.3
ide-haskell, v0.5.6
japanese-wrap, v0.2.7
language-batch, v0.3.3
language-cmake, v0.1.3
language-csharp, v0.5.0
language-d, v3.2.1
language-dart, v0.2.0
language-fish-shell, v1.0.2
language-generic-config, v0.2.0
language-haml, v0.21.0
language-lisp, v0.1.1
language-plantuml, v0.0.0
language-rust, v0.4.3
language-scala, v1.1.0
language-scheme, v1.4.0
language-slim, v0.4.0
language-smalltalk, v1.0.2
language-svg, v0.8.0
language-swift, v0.4.0
language-textile, v0.2.0
language-typescript, v0.15.0
linter, v0.12.6
linter-clang, v2.25.2
linter-coffeelint, v0.2.4
linter-rubocop, v0.2.7
linter-ruby, v0.1.6
minimap, v4.9.0
pigments, v0.3.1
project-palette-finder, v2.4.17
regex-railroad-diagram, v0.7.4
show-ideographic-space, v0.1.7
svg-preview, v0.6.0
symbols-tree-view, v0.9.3
web-view, v0.3.0

# Dev
No dev packages
```

**Comment by raccy** [comment]
コメントが行や空白行がある複数行をコピー＆ペーストすると駄目っぽい。
現象起きた人は、しばらくまってください(または、プルリクおくって＞＜)

**Comment by raccy** [comment]
Atom側のAPIが変わって、根本的に動かないことが判明しました。
そっちに統合してますので、 そちらを見てください。 #7
なお、0.1.8は幻となります。
